name: CI - Docker

on: ["push"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Push to Registry
        env:
          IMAGE_NAME: archongum/livy-bin:0.8.0-snapshot-scala2.12-spark3-hadoop3
        run: |
          # show size
          du -sh ./*
          # build
          docker build . -f Dockerfile --tag $IMAGE_NAME
          # show images
          docker images | head -n 10
          # push
          docker push $IMAGE_NAME
